name: Builds, tests & co

on:
  push:
  pull_request:

permissions: read-all

jobs:
  main: # Объединяем все в одно задание
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        # Легко добавить другие версии OCaml для тестирования в будущем
        ocaml-compiler: [ "5.1" ] # Рекомендуется использовать конкретную версию

    steps:
      - name: Checkout tree
        uses: actions/checkout@v5

      - name: Set-up OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          # Кэширование значительно ускорит последующие запуски
          cache-opam: true

      - name: Install dependencies
        run: opam install . --deps-only --with-test

      - name: Check opam file linting
        # Заменяет lint-opam
        run: opam lint

      - name: Check code formatting
        # Заменяет lint-fmt и исправляет ошибку
        # Убедитесь, что ocamlformat указан как зависимость в opam/dune-project файлах
        run: opam exec -- dune fmt --check

      - name: Build project
        run: opam exec -- dune build

      - name: Run tests
        run: opam exec -- dune runtest

      - name: Build documentation
        # Заменяет lint-doc. Этот шаг проверяет, что документация собирается.
        run: opam exec -- dune build @doc