name: OCaml CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        ocaml-compiler: ["4"]
        task: ["Task14", "Task16"]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - name: Install dependencies
        run: opam install . --deps-only --with-test --with-dev-setup
        working-directory: ./Lab1/${{ matrix.task }}

      - name: Check formatting
        run: opam exec -- dune fmt
        working-directory: ./Lab1/${{ matrix.task }}

      - name: Build project
        run: opam exec -- dune build
        working-directory: ./Lab1/${{ matrix.task }}

      - name: Increase stack size
        run: ulimit -s unlimited

      - name: Run tests
        run: opam exec -- dune run
        working-directory: ./Lab1/${{ matrix.task }}